# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    # workaround for failure to create private networks or port forwarding
    # See https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1389
    libvirt.qemu_use_session = false
  end
  config.vm.box = "generic-x64/debian12"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.verbose = "vv"
    ansible.extra_vars = {
      flask_secret_key: ENV['FLASK_SECRET_KEY']
    }
  end
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
end
