---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: warpnet-challenge:0.2.0
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: flask-secret-key
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "60Mi"
            cpu: "70m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: warpnet-service
spec:
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
