---
name: Quality checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r app/requirements-dev.txt
      # note: ruff is also available as a GH action. Depending on the policy, one might want to avoid
      # using untrusted actions.
      - name: Run linter
        run: ruff check app/
      - name: Check formatting
        run: ruff format --check --diff
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dockerfile linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Build docker image
        run: docker build -t image:${{ github.sha }} .
      - name: Check for image vulnerabilities
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: image:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
